// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tokenizer_maps.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from tokenizer_maps.proto</summary>
public static partial class TokenizerMapsReflection {

  #region Descriptor
  /// <summary>File descriptor for tokenizer_maps.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TokenizerMapsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChR0b2tlbml6ZXJfbWFwcy5wcm90byLWAwoNVG9rZW5pemVyTWFwcxIsCgdU",
          "ZXh0TWFwGAEgAygLMhsuVG9rZW5pemVyTWFwcy5UZXh0TWFwRW50cnkSOAoN",
          "U3BlY2lhbFRva2VucxgCIAMoCzIhLlRva2VuaXplck1hcHMuU3BlY2lhbFRv",
          "a2Vuc0VudHJ5EiwKB1JhbmtNYXAYAyADKAsyGy5Ub2tlbml6ZXJNYXBzLlJh",
          "bmtNYXBFbnRyeRJGChRJbnZlcnNlU3BlY2lhbFRva2VucxgEIAMoCzIoLlRv",
          "a2VuaXplck1hcHMuSW52ZXJzZVNwZWNpYWxUb2tlbnNFbnRyeRIUCgxSZWdl",
          "eFBhdHRlcm4YBSABKAkaLgoMVGV4dE1hcEVudHJ5EgsKA2tleRgBIAEoBRIN",
          "CgV2YWx1ZRgCIAEoDDoCOAEaNAoSU3BlY2lhbFRva2Vuc0VudHJ5EgsKA2tl",
          "eRgBIAEoCRINCgV2YWx1ZRgCIAEoBToCOAEaLgoMUmFua01hcEVudHJ5EgsK",
          "A2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoBToCOAEaOwoZSW52ZXJzZVNwZWNp",
          "YWxUb2tlbnNFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAw6AjgB",
          "YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::TokenizerMaps), global::TokenizerMaps.Parser, new[]{ "TextMap", "SpecialTokens", "RankMap", "InverseSpecialTokens", "RegexPattern" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, })
        }));
  }
  #endregion

}
#region Messages
public sealed partial class TokenizerMaps : pb::IMessage<TokenizerMaps>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<TokenizerMaps> _parser = new pb::MessageParser<TokenizerMaps>(() => new TokenizerMaps());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<TokenizerMaps> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TokenizerMapsReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TokenizerMaps() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TokenizerMaps(TokenizerMaps other) : this() {
    textMap_ = other.textMap_.Clone();
    specialTokens_ = other.specialTokens_.Clone();
    rankMap_ = other.rankMap_.Clone();
    inverseSpecialTokens_ = other.inverseSpecialTokens_.Clone();
    regexPattern_ = other.regexPattern_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TokenizerMaps Clone() {
    return new TokenizerMaps(this);
  }

  /// <summary>Field number for the "TextMap" field.</summary>
  public const int TextMapFieldNumber = 1;
  private static readonly pbc::MapField<int, pb::ByteString>.Codec _map_textMap_codec
      = new pbc::MapField<int, pb::ByteString>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBytes(18, pb::ByteString.Empty), 10);
  private readonly pbc::MapField<int, pb::ByteString> textMap_ = new pbc::MapField<int, pb::ByteString>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<int, pb::ByteString> TextMap {
    get { return textMap_; }
  }

  /// <summary>Field number for the "SpecialTokens" field.</summary>
  public const int SpecialTokensFieldNumber = 2;
  private static readonly pbc::MapField<string, int>.Codec _map_specialTokens_codec
      = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 18);
  private readonly pbc::MapField<string, int> specialTokens_ = new pbc::MapField<string, int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, int> SpecialTokens {
    get { return specialTokens_; }
  }

  /// <summary>Field number for the "RankMap" field.</summary>
  public const int RankMapFieldNumber = 3;
  private static readonly pbc::MapField<string, int>.Codec _map_rankMap_codec
      = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 26);
  private readonly pbc::MapField<string, int> rankMap_ = new pbc::MapField<string, int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, int> RankMap {
    get { return rankMap_; }
  }

  /// <summary>Field number for the "InverseSpecialTokens" field.</summary>
  public const int InverseSpecialTokensFieldNumber = 4;
  private static readonly pbc::MapField<int, pb::ByteString>.Codec _map_inverseSpecialTokens_codec
      = new pbc::MapField<int, pb::ByteString>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBytes(18, pb::ByteString.Empty), 34);
  private readonly pbc::MapField<int, pb::ByteString> inverseSpecialTokens_ = new pbc::MapField<int, pb::ByteString>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<int, pb::ByteString> InverseSpecialTokens {
    get { return inverseSpecialTokens_; }
  }

  /// <summary>Field number for the "RegexPattern" field.</summary>
  public const int RegexPatternFieldNumber = 5;
  private string regexPattern_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RegexPattern {
    get { return regexPattern_; }
    set {
      regexPattern_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as TokenizerMaps);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(TokenizerMaps other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!TextMap.Equals(other.TextMap)) return false;
    if (!SpecialTokens.Equals(other.SpecialTokens)) return false;
    if (!RankMap.Equals(other.RankMap)) return false;
    if (!InverseSpecialTokens.Equals(other.InverseSpecialTokens)) return false;
    if (RegexPattern != other.RegexPattern) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= TextMap.GetHashCode();
    hash ^= SpecialTokens.GetHashCode();
    hash ^= RankMap.GetHashCode();
    hash ^= InverseSpecialTokens.GetHashCode();
    if (RegexPattern.Length != 0) hash ^= RegexPattern.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    textMap_.WriteTo(output, _map_textMap_codec);
    specialTokens_.WriteTo(output, _map_specialTokens_codec);
    rankMap_.WriteTo(output, _map_rankMap_codec);
    inverseSpecialTokens_.WriteTo(output, _map_inverseSpecialTokens_codec);
    if (RegexPattern.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(RegexPattern);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    textMap_.WriteTo(ref output, _map_textMap_codec);
    specialTokens_.WriteTo(ref output, _map_specialTokens_codec);
    rankMap_.WriteTo(ref output, _map_rankMap_codec);
    inverseSpecialTokens_.WriteTo(ref output, _map_inverseSpecialTokens_codec);
    if (RegexPattern.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(RegexPattern);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += textMap_.CalculateSize(_map_textMap_codec);
    size += specialTokens_.CalculateSize(_map_specialTokens_codec);
    size += rankMap_.CalculateSize(_map_rankMap_codec);
    size += inverseSpecialTokens_.CalculateSize(_map_inverseSpecialTokens_codec);
    if (RegexPattern.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RegexPattern);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(TokenizerMaps other) {
    if (other == null) {
      return;
    }
    textMap_.MergeFrom(other.textMap_);
    specialTokens_.MergeFrom(other.specialTokens_);
    rankMap_.MergeFrom(other.rankMap_);
    inverseSpecialTokens_.MergeFrom(other.inverseSpecialTokens_);
    if (other.RegexPattern.Length != 0) {
      RegexPattern = other.RegexPattern;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          textMap_.AddEntriesFrom(input, _map_textMap_codec);
          break;
        }
        case 18: {
          specialTokens_.AddEntriesFrom(input, _map_specialTokens_codec);
          break;
        }
        case 26: {
          rankMap_.AddEntriesFrom(input, _map_rankMap_codec);
          break;
        }
        case 34: {
          inverseSpecialTokens_.AddEntriesFrom(input, _map_inverseSpecialTokens_codec);
          break;
        }
        case 42: {
          RegexPattern = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          textMap_.AddEntriesFrom(ref input, _map_textMap_codec);
          break;
        }
        case 18: {
          specialTokens_.AddEntriesFrom(ref input, _map_specialTokens_codec);
          break;
        }
        case 26: {
          rankMap_.AddEntriesFrom(ref input, _map_rankMap_codec);
          break;
        }
        case 34: {
          inverseSpecialTokens_.AddEntriesFrom(ref input, _map_inverseSpecialTokens_codec);
          break;
        }
        case 42: {
          RegexPattern = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
